require: rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  Exclude:
    - "_/**/*"

Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
    - "*.gemspec"
  IgnoredMethods:
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - guard
    - included
    - it
    - let
    - let!
    - scenario
    - setup
    - shared_context
    - shared_examples
    - shared_examples_for
    - transaction

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 200
  # Ignores annotate output
  IgnoredPatterns: ['\A# \*\*']
  IgnoreCopDirectives: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Style/BlockComments:
  Enabled: false
  Include:
    - "**/spec/*"

# New Cops - Start
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
# New Cops - Start

# My Preferences - Start
Metrics/ClassLength:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  Exclude:
    - "**/spec/**/*"
Style/EmptyMethod:    
  Exclude:
    - "**/spec/**/*"
Metrics/ParameterLists:
  Exclude:
    - "**/spec/**/*"
Layout/EmptyLineBetweenDefs:
  Exclude:
    - "**/spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"

Style/AccessorGrouping:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false
# My Preferences - End

